export const TEAM_INFO = [
  {
    name: "Andrey Ratov",
    position: "CEO",
    head: true,
    href: "https://linkedin.com",
    img: "/assets/team/Andrey.png",
  },
  {
    name: "Junichi Kimura",
    position: "Partner",
    head: false,
    href: "https://linkedin.com",
    img: "/assets/team/Junichi.png",
  },
  {
    name: "Tres Cunningham",
    position: "Ambassador",
    head: false,
    href: "https://linkedin.com",
    img: "/assets/team/Tres.png",
  },
  {
    name: "Artem Telgerekov",
    position: "Project Manager",
    head: false,
    href: "https://linkedin.com",
    img: "/assets/team/Artem.png",
  },
  {
    name: "Juliya Khohlova",
    position: "Designer",
    head: false,
    href: "https://linkedin.com",
    img: "/assets/team/Julia.png",
  },
  {
    name: "Igor N.",
    position: "CTO",
    head: false,
    href: "",
    img: "/assets/team/Igor.png",
  },
  {
    name: "Lisa Adinagueva",
    position: "Web-designer",
    head: false,
    href: "",
    img: "/assets/team/Lisa.png",
  },
  {
    name: "Vasiliy Popov",
    position: "Producer",
    head: false,
    inst: "https://instagram.com",
    img: "/assets/team/Vasiliy.png",
  },
];
